---
# - name: Add indicator-sound-switcher repository
#   apt_repository:
#     repo: 'ppa:yktooo/ppa/ubuntu jammy main'
#     state: present

- name: Agree to EULA
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    vtype: boolean
    value: true

- name: Install packages
  apt: 
    name:
      - android-sdk-platform-tools
      - bat
      - devilspie2
      - fzf
      - git
      - glibc-source
      - gparted
      - htop
      - indicator-sound-switcher
      - jq
      - nala
      - neofetch
      - npm
      - openssh-client
      - openssh-server
      - redshift
      - ripgrep
      - rofi
      - steam
      - stow
      - tmux
      - ttf-mscorefonts-installer
      - ufw
      - vim-gtk3
      - xclip
      - zsh
    state: latest

- name: Install n
  command: npm install -g n

- name: Update global npm version
  command: n latest

- name: Install Flatpaks
  flatpak:
    name: "{{ item.name }}"
    state: present
  loop:
    - { name: 'com.discordapp.Discord' }
    - { name: 'com.getpostman.Postman' }
    - { name: 'com.obsproject.Studio' }
    - { name: 'md.obsidian.Obsidian' }
    - { name: 'org.DolphinEmu.dolphin-emu' }
    - { name: 'org.onlyoffice.desktopeditors' }

- name: Update Flatpaks
  command: flatpak update -y

- name: Install Qemu/Virt-Manager
  apt:
    name:
      - bridge-utils
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system
      - python3
      - python3-pip
      - qemu-kvm
      - qemu-system
      - qemu-utils
      - virt-manager
      - virtinst

- name: Add user to VM groups
  user:
    name: ryan
    groups: libvirt,libvirt-qemu,kvm,input,disk
    append: yes

- name: Remove unwanted packages
  apt:
    name:
      - drawing
      - 'libreoffice*'
      - hexchat
      - hypnotix
      - redshift-gtk
      - rhythmbox
      - rhythmbox-plugins
      - rhythmbox-plugin-tray-icon
      - sticky
      - thingy
      - 'thunderbird*'
      - transmission-gtk
      - warpinator
      - xed-dbg
      - xed
      - virt-viewer 
      - libgovirt-common 
      - libgovirt2 
    state: absent
    purge: true
    
- name: Install Visual Studio Code
  apt:
    deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Clean
  apt:
    autoclean: yes
