- name: Deny incoming traffic
  ufw:
    default: deny
    direction: incoming
  ignore_errors: true

- name: Allow outgoing traffic
  ufw:
    default: allow
    direction: outgoing
  ignore_errors: true

- name: Enable firewall
  ufw:
    state: enabled

- name: Start SSH service
  service:
    state: started
    name: sshd

- name: Enable SSH service
  service:
    name: sshd
    enabled: true

- name: Allow SSH traffic
  ufw:
    rule: allow
    name: OpenSSH

- name: Reload firewall
  ufw:
    state: reloaded
