- name: Create test dir
  debug:
    var: ansible_kernel 
  # when: ansible_facts.distribution == 'Linux Mint'
   
- name: Get latest release information from GitHub API
  uri:
    url: https://api.github.com/repos/project-slippi/slippi-launcher/releases/latest
    return_content: yes
  register: slippi_response

- name: Parse JSON response to extract AppImage URL
  ansible.builtin.set_fact:
    appimage_url: "{{ slippi_response | json_query(slippi_query) }}"
  vars: 
    slippi_query: "json.assets[?ends_with(name, '.AppImage')].browser_download_url"

- name: Download the latest AppImage
  ansible.builtin.get_url:
    url: "{{ appimage_url[0] }}"
    dest: /home/ryan/Downloads
